import Head from "next/head";
import { BsFillMoonStarsFill } from "../node_modules/react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import code from "../public/wrench1.jpg";
import design from "../public/front.png";
import consulting from "../public/consultant.jpg";
import dice from "../public/dice.png";
import pingpong from "../public/pingpong.png";
import yelp from "../public/yelp.png";
import takota from "../public/takota.png";
import shop from "../public/shop.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>RS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-lg font-burtons dark:text-white md:text-xl">
              DevelopedByRustam
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  href="https://www.linkedin.com/in/rustamsapayev/"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Rustam Sapayev
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-teal-600 md:text-xl max-w-lg mx-auto">
              I'm a Web Developer based in Cincinnati, Ohio. I'm passionate
              about creating intuitive, dynamic UX and interesting web
              applications. Independent problem-solver with meticulous attention
              to details. Consistently enthusiastic about engaging in ambitious
              projects alongside dynamic individuals.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3">
            <a href="https://twitter.com/rustamofficial">
              <AiFillTwitterCircle />
            </a>

            <a href="https://www.linkedin.com/in/rustamsapayev/">
              <AiFillLinkedin />
            </a>

            <AiFillYoutube />
          </div>
        </section>
        <section>
          <div className="lg:flex gap-10 dark:text-white">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Front-end development
              </h3>
              <p className="py-2">
                My expertise lies in crafting responsive websites that
                seamlessly adapt to various devices and deliver swift,
                user-friendly experiences. I employ a range of technologies such
                as:
              </p>
              <ul className="dark:text-teal-500">
                <li>-HTML</li>
                <li>-CSS</li>
                <li>-Bootstrap</li>
                <li>-Bulma</li>
                <li>-Express.js</li>
                <li>-TailwindCSS</li>
                <li>-Wordpress</li>
                <li>-Photoshop</li>
                <li>-SASS</li>
              </ul>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Front-end development
              </h3>
              <p className="py-2">
                My expertise lies in crafting responsive websites that
                seamlessly adapt to various devices and deliver swift,
                user-friendly experiences. I employ a range of technologies such
                as:
              </p>
              <ul className="dark:text-teal-500">
                <li>-HTML</li>
                <li>-CSS</li>
                <li>-Bootstrap</li>
                <li>-Bulma</li>
                <li>-Express.js</li>
                <li>-TailwindCSS</li>
                <li>-Wordpress</li>
                <li>-Photoshop</li>
                <li>-SASS</li>
              </ul>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Front-end development
              </h3>
              <p className="py-2">
                My expertise lies in crafting responsive websites that
                seamlessly adapt to various devices and deliver swift,
                user-friendly experiences. I employ a range of technologies such
                as:
              </p>
              <ul className="dark:text-teal-500">
                <li>-HTML</li>
                <li>-CSS</li>
                <li>-Bootstrap</li>
                <li>-Bulma</li>
                <li>-Express.js</li>
                <li>-TailwindCSS</li>
                <li>-Wordpress</li>
                <li>-Photoshop</li>
                <li>-SASS</li>
              </ul>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
